ENTRYPOINTS=kitchen tests

test:
	coverage run -m pytest -s --rootdir tests

report:
	coverage report

tox:
	tox

lint:
	flake8 $(ENTRYPOINTS)
	mypy $(ENTRYPOINTS)

check:
	black --check $(ENTRYPOINTS)
	isort --check $(ENTRYPOINTS)

format:
	black $(ENTRYPOINTS)
	isort $(ENTRYPOINTS)

